<!DOCTYPE html>
<html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>謇句ｽ楢ｨｭ螳・/title>
<style>body{font-family:"Segoe UI","Hiragino Kaku Gothic ProN",Meiryo,sans-serif;background:#ecf2fb;margin:0;padding:18px}.card{background:#fff;border:1px solid #d3dff0;border-radius:14px;padding:16px}.btn{display:inline-flex;padding:8px 12px;border:1px solid #b7ccef;border-radius:10px;background:#e7effc;color:#1f4f8f;text-decoration:none;font-weight:700}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{border:1px solid #d3dff0;padding:6px;white-space:nowrap;text-align:center}th{background:#f5f8fd}.wrap{overflow:auto}input,select,button{padding:6px 8px;border:1px solid #d3dff0;border-radius:8px}button{background:#1f4f8f;color:#fff;border-color:#1f4f8f}</style></head>
<body><div class="card"><div style="display:flex;justify-content:space-between;flex-wrap:wrap;gap:8px;align-items:center;"><h2 style="margin:0;">謇句ｽ楢ｨｭ螳・/h2><div style="display:flex;gap:8px;flex-wrap:wrap"><a class="btn" href="{{ route('admin.master.company') }}">莨夂､ｾ繝槭せ繧ｿ</a><a class="btn" href="{{ route('admin.master.staff') }}">繧ｹ繧ｿ繝・ヵ繝槭せ繧ｿ</a><a class="btn" href="{{ route('admin.master.store') }}">蠎苓・繝槭せ繧ｿ</a><a class="btn" href="{{ route('admin.dashboard') }}">繝繝・す繝･繝懊・繝・/a></div></div>
@if(session('status'))<p>{{ session('status') }}</p>@endif
<form method="get" style="margin-top:8px;display:flex;gap:8px;align-items:center;"><label>莨夂､ｾ:</label><select name="office_name"><option value="">蜈ｨ莨夂､ｾ</option>@foreach($companyOptions as $c)<option value="{{ $c['company_code'] }}" @selected($selectedOfficeName===$c['company_code'])>{{ $c['company_code'] }} {{ $c['company_name'] }}</option>@endforeach</select><button type="submit">陦ｨ遉ｺ</button></form>

<p>莉ｶ謨ｰ: {{ number_format($rowCount) }} / 繧ｽ繝ｼ繧ｹ: {{ $source }}</p>
<div class="wrap"><table><thead><tr><th>No</th><th>莨夂､ｾ</th><th>陦ｨ遉ｺ鬆・/th><th>AmountKey</th><th>謇句ｽ灘錐</th><th>蜉ｴ菫・/th><th>遉ｾ菫・/th><th>遞・/th><th>蝗ｺ螳・/th><th>蜑ｲ蠅・/th><th>謗ｧ髯､</th><th>菫晏ｭ・/th></tr></thead><tbody>
@forelse($rows as $row)
<tr><form method="post" action="{{ route('admin.master.allowance.update') }}">@csrf<input type="hidden" name="allowance_no" value="{{ $row['allowance_no'] }}"><input type="hidden" name="office_name_filter" value="{{ $selectedOfficeName }}"><td>{{ $row['allowance_no'] }}</td><td>{{ $row['office_name'] }}</td><td><input type="number" name="display_order" min="1" max="999" value="{{ $row['display_order'] }}" style="width:70px"></td><td><input type="text" name="amount_column_key" value="{{ $row['amount_column_key'] }}"></td><td><input type="text" name="allowance_name" value="{{ $row['allowance_name'] }}"></td><td><input type="checkbox" name="rou_target" value="1" @checked((int)$row['rou_target']===1)></td><td><input type="checkbox" name="syaho_target" value="1" @checked((int)$row['syaho_target']===1)></td><td><input type="checkbox" name="tax_target" value="1" @checked((int)$row['tax_target']===1)></td><td><input type="checkbox" name="kotei_wage" value="1" @checked((int)$row['kotei_wage']===1)></td><td><input type="checkbox" name="warimasi_kiso" value="1" @checked((int)$row['warimasi_kiso']===1)></td><td><input type="checkbox" name="koujyo_kiso" value="1" @checked((int)$row['koujyo_kiso']===1)></td><td><button type="submit">譖ｴ譁ｰ</button></td></form></tr>
@empty<tr><td colspan="12">繝・・繧ｿ縺後≠繧翫∪縺帙ｓ</td></tr>@endforelse
</tbody></table></div></div></body></html>