<!DOCTYPE html>
<html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>店舗マスタ</title>
<style>body{font-family:"Segoe UI","Hiragino Kaku Gothic ProN",Meiryo,sans-serif;background:#ecf2fb;margin:0;padding:18px}.card{background:#fff;border:1px solid #d3dff0;border-radius:14px;padding:16px}.btn{display:inline-flex;padding:8px 12px;border:1px solid #b7ccef;border-radius:10px;background:#e7effc;color:#1f4f8f;text-decoration:none;font-weight:700}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{border:1px solid #d3dff0;padding:6px;white-space:nowrap;text-align:center}th{background:#f5f8fd}input,select,button{padding:6px 8px;border:1px solid #d3dff0;border-radius:8px}button{background:#1f4f8f;color:#fff;border-color:#1f4f8f}.wrap{overflow:auto}</style></head>
<body><div class="card">
<div style="display:flex;justify-content:space-between;flex-wrap:wrap;gap:8px;align-items:center;"><h2 style="margin:0;">店舗マスタ</h2><div style="display:flex;gap:8px;flex-wrap:wrap"><a class="btn" href="{{ route('admin.master.company') }}">会社マスタ</a><a class="btn" href="{{ route('admin.master.staff') }}">スタッフマスタ</a><a class="btn" href="{{ route('admin.master.allowance') }}">手当設定</a><a class="btn" href="{{ route('admin.dashboard') }}">ダッシュボード</a></div></div>
@if(session('status'))<p>{{ session('status') }}</p>@endif
<form method="get" style="margin-top:8px;display:flex;gap:8px;"><input type="text" name="q" value="{{ $keyword }}" placeholder="店舗コード/店舗名/会社名"><button type="submit">検索</button></form>
<p>件数: {{ number_format($rowCount) }} / ソース: {{ $source }}</p>
<div class="wrap"><table><thead><tr><th>店舗コード</th><th>店舗名</th><th>会社</th><th>略称</th><th>電話</th><th>休止</th><th>Legacy</th><th>保存</th></tr></thead><tbody>
@forelse($rows as $row)
<tr><form method="post" action="{{ route('admin.master.store.update') }}">@csrf<input type="hidden" name="store_code" value="{{ $row['store_code'] }}"><input type="hidden" name="q" value="{{ $keyword }}"><td>{{ $row['store_code'] }}</td><td><input type="text" name="store_name" value="{{ $row['store_name'] }}"></td><td><select name="company_id"><option value="">(未設定)</option>@foreach($companyOptions as $c)<option value="{{ $c['company_id'] }}" @selected($c['company_id']===$row['company_id'])>{{ $c['company_name'] }}</option>@endforeach</select></td><td><input type="text" name="store_short_name" value="{{ $row['store_short_name'] }}"></td><td><input type="text" name="phone" value="{{ $row['phone'] }}"></td><td><select name="is_closed"><option value="0" @selected((int)$row['is_closed']===0)>0</option><option value="1" @selected((int)$row['is_closed']===1)>1</option></select></td><td>{{ $row['legacy_no'] }}</td><td><button type="submit">更新</button></td></form></tr>
@empty<tr><td colspan="8">データがありません</td></tr>@endforelse
</tbody></table></div></div></body></html>