<!DOCTYPE html>
<html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>スタッフマスタ</title>
<style>body{font-family:"Segoe UI","Hiragino Kaku Gothic ProN",Meiryo,sans-serif;background:#ecf2fb;margin:0;padding:18px}.card{background:#fff;border:1px solid #d3dff0;border-radius:14px;padding:16px}.btn{display:inline-flex;padding:8px 12px;border:1px solid #b7ccef;border-radius:10px;background:#e7effc;color:#1f4f8f;text-decoration:none;font-weight:700}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{border:1px solid #d3dff0;padding:6px;white-space:nowrap;text-align:center}th{background:#f5f8fd}.wrap{overflow:auto}input,button{padding:6px 8px;border:1px solid #d3dff0;border-radius:8px}button{background:#1f4f8f;color:#fff;border-color:#1f4f8f}</style></head>
<body><div class="card"><div style="display:flex;justify-content:space-between;flex-wrap:wrap;gap:8px;align-items:center;"><h2 style="margin:0;">スタッフマスタ</h2><div style="display:flex;gap:8px;flex-wrap:wrap"><a class="btn" href="{{ route('admin.master.company') }}">会社マスタ</a><a class="btn" href="{{ route('admin.master.store') }}">店舗マスタ</a><a class="btn" href="{{ route('admin.master.allowance') }}">手当設定</a><a class="btn" href="{{ route('admin.dashboard') }}">ダッシュボード</a></div></div>
<form method="get" style="margin-top:8px;display:flex;gap:8px;"><input type="text" name="q" value="{{ $keyword }}" placeholder="ID/氏名/店舗コード"><button type="submit">検索</button></form>
<p>件数: {{ number_format($rowCount) }} / ソース: {{ $source }}</p>
<div class="wrap"><table><thead><tr><th>ID</th><th>氏名</th><th>カナ</th><th>店舗コード</th><th>店舗名</th><th>雇用</th><th>店舗管理</th><th>日報</th><th>退職日</th></tr></thead><tbody>
@forelse($rows as $row)
<tr><td>{{ $row['staff_id'] }}</td><td>{{ $row['staff_name'] }}</td><td>{{ $row['staff_name_kana'] }}</td><td>{{ $row['store_code'] }}</td><td>{{ $row['store_name'] }}</td><td>{{ $row['employment_status'] }}</td><td>{{ (int)$row['is_store_manager']===1 ? '1' : '0' }}</td><td>{{ (int)$row['is_daily_report_user']===1 ? '1' : '0' }}</td><td>{{ $row['retire_date'] }}</td></tr>
@empty<tr><td colspan="9">データがありません</td></tr>@endforelse
</tbody></table></div></div></body></html>